config/routes.rb
Mwit::Application.routes.draw do

  resources :mwit
  root :to => redirect('/mwit')

  resources :welcome

  resources :group_permissions

  resources :group_vals

  resources :user_groups

  resources :users

  resources :posts

end

app/models/group_val.rb
class GroupVal < ActiveRecord::Base
end

app/controllers/group_vals_controller.rb
class GroupValsController < ApplicationController
  # GET /group_vals
  # GET /group_vals.json
  def index
    @group_vals = GroupVal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @group_vals }
    end
  end

  # GET /group_vals/1
  # GET /group_vals/1.json
  def show
    @group_val = GroupVal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group_val }
    end
  end

  # GET /group_vals/new
  # GET /group_vals/new.json
  def new
    @group_val = GroupVal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group_val }
    end
  end

  # GET /group_vals/1/edit
  def edit
    @group_val = GroupVal.find(params[:id])
  end

  # POST /group_vals
  # POST /group_vals.json
  def create
    @group_val = GroupVal.new(params[:group_val])

    respond_to do |format|
      if @group_val.save
        format.html { redirect_to @group_val, notice: 'Group val was successfully created.' }
        format.json { render json: @group_val, status: :created, location: @group_val }
      else
        format.html { render action: "new" }
        format.json { render json: @group_val.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /group_vals/1
  # PUT /group_vals/1.json
  def update
    @group_val = GroupVal.find(params[:id])

    respond_to do |format|
      if @group_val.update_attributes(params[:group_val])
        format.html { redirect_to @group_val, notice: 'Group val was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group_val.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_vals/1
  # DELETE /group_vals/1.json
  def destroy
    @group_val = GroupVal.find(params[:id])
    @group_val.destroy

    respond_to do |format|
      format.html { redirect_to group_vals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/group_vals_helper.rb
module GroupValsHelper
end

app/views/group_vals/_form.html.erb
<%= form_for(@group_val) do |f| %>
  <% if @group_val.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group_val.errors.count, "error") %> prohibited this group_val from being saved:</h2>

      <ul>
      <% @group_val.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/group_vals/edit.html.erb
<h1>Editing group_val</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_val %> |
<%= link_to 'Back', group_vals_path %>

app/views/group_vals/index.html.erb
<h1>Listing group_vals</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @group_vals.each do |group_val| %>
  <tr>
    <td><%= group_val.type %></td>
    <td><%= group_val.description %></td>
    <td><%= link_to 'Show', group_val %></td>
    <td><%= link_to 'Edit', edit_group_val_path(group_val) %></td>
    <td><%= link_to 'Destroy', group_val, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group val', new_group_val_path %>

app/views/group_vals/new.html.erb
<h1>New group_val</h1>

<%= render 'form' %>

<%= link_to 'Back', group_vals_path %>

app/views/group_vals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @group_val.type %>
</p>

<p>
  <b>Description:</b>
  <%= @group_val.description %>
</p>


<%= link_to 'Edit', edit_group_val_path(@group_val) %> |
<%= link_to 'Back', group_vals_path %>