config/routes.rb
Mwit::Application.routes.draw do

  resources :mwit
  root :to => redirect('/mwit')

  resources :welcome

  resources :group_permissions

  resources :group_vals

  resources :user_groups

  resources :users

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :post_type, :detail, :post_date, :event_date, 
					:user_post_id, :user_id, :created_at, :updated_at, :exp_date,
					:deleted
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    # MOD KIMADA 3/31/2013
    #@posts = Post.all    
    @posts = Post.where(['DATE(exp_date) >= ?', Date.today])
    #

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end



  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    # aross 4/02/2013 adding in hidden parameters (do i do it here on on screen?)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/Old_new.html.haml
%table{:class => "top"}
  %tbody
    %tr
      %td= image_tag "mwit_logo.jpg", :class => "logo"
      %td{:class => "mwit"} Mills Women in Technology - Create New Post
      %td
      %td 
        %table
          %tbody
            %tr
              %td Login
              %td Sign-Up
%br
%br
-@@today = Date.current
-@@event_date
%table 
  %tbody
  = form_tag posts_path do
    %tr
      %td= label :post, :post_type, 'Select Post type',:align=> "right"
      %td= select :post, :post_type, ['Job','Internship','Event','Scholarship']
      %td
    %tr
      %td= label :post, :title, 'Title'
      %td= text_field :title, 'title'
      %td= submit_tag 'Save Changes'
    %tr
      %td= label :post, :detail, 'Details'
      %td= text_field :detail, 'detail'
      %td= button_to 'Cancel', posts_path
    %tr
      %td= label :post, :post_date, 'Date'
      %td= date_select(:event_date, :post)
      %td= hidden_field :post, :created_at, value: @today#, :updated_at = Time.now
      
      

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td ><%#= f.label :title %>
      </td>
      <td><%#= f.text_field :title %></td></tr>
  </table>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post_type %><br />
    <%= f.text_field :post_type %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail, :row => 10, :cols =>15  %>
  </div>
  <div class="field">
    <%= f.label :post_date %><br />
    <%= f.date_select :post_date %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br />
    <%= f.date_select :event_date %>
  </div>
  <div class="field">
    <%= f.label :exp_date %><br />
    <%= f.date_select :exp_date %>
  </div>
  <div class="field">
    <%= f.label :user_post_id %><br />
    <%= f.number_field :user_post_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
-#  KIMADA 3/31/2013 Added Top Area to Postings Page and Convert to HAML
%table{:class => "top"}
    %tbody
        %tr
            %td= image_tag "mwit_logo.jpg", :class => "logo"
            %td= link_to "New Post", new_post_path, :class => "top"
            %td{:class => "mwit"} Mills Women in Technology
            %td
            %td= link_to "Home", mwit_index_path, :class => "top"
            %td{:class => "top"} Logout

%h1 Postings

%p{:id => "notice"}= notice

%table
    %thead
        %th Title
        %th Post Type
        %th Detail
        %th Post Date
        %th Event Date
        %th Expiration Date
    %tbody
        - @posts.each do |post|
            %tr
                %td= post.title
                %td= post.post_type
                %td= post.detail
                %td= post.post_date
                %td= post.event_date
                %td= post.exp_date
                %td= link_to 'Show', post
                %td= link_to 'Edit', edit_post_path(post)
                %td= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Post Type:</b>
  <%= @post.post_type %>
</p>

<p>
  <b>Detail:</b>
  <%= @post.detail %>
</p>

<p>
  <b>Post date:</b>
  <%= @post.post_date %>
</p>

<p>
  <b>Event date:</b>
  <%= @post.event_date %>
</p>

<p>
  <b>Exp date:</b>
  <%= @post.exp_date %>
</p>

<p>
  <b>User post:</b>
  <%= @post.user_post_id %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>